---
queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success-or-neutral=Deadpendency Check

pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - base=main
      - author~=github-actions
      - check-success-or-neutral=Deadpendency Check
    actions:
      queue:
        method: merge
        name: default
  - name: automatic merge for Dependabot pull requests
    conditions:
      - base=main
      - author~=dependabot
      - check-success-or-neutral=Deadpendency Check
    actions:
      queue:
        method: merge
        name: default
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
