---
pull_request_rules:
  - name: automatic merge on CI success and review
    conditions:
      - base=master
      - label!=work-in-progress
      - check-success=add-recent-github-activity
      - check-success=update-readme-with-blog
      - check-success=compress-images
      - check-success=github-actions
    actions:
      merge:
        method: merge
        strict: smart
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success=add-recent-github-activity
      - check-success=update-readme-with-blog
      - check-success=compress-images
      - check-success=github-actions
    actions:
      merge:
        method: merge
  - name: automatic merge for ImgBot pull requests
    conditions:
      - author=imgbot[bot]
      - check-success=add-recent-github-activity
      - check-success=update-readme-with-blog
      - check-success=compress-images
      - check-success=github-actions
    actions:
      merge:
        method: merge
  - name: automatic merge for Snyk pull requests
    conditions:
      - title~=^\[Snyk\]
      - head~=^snyk-fix
      - check-success~=^security/snyk
      - check-success=add-recent-github-activity
      - check-success=update-readme-with-blog
      - check-success=compress-images
      - check-success=github-actions
    actions:
      merge:
        method: merge
  - name: automatic merge for Requires.io pull requests
    conditions:
      - title~=^\[requires.io\]
      - head~=^requires-io
      - check-success=add-recent-github-activity
      - check-success=update-readme-with-blog
      - check-success=compress-images
      - check-success=github-actions
    actions:
      merge:
        method: merge
  - name: automatic merge for PyUp pull requests
    conditions:
      - author=pyup-bot
      - check-success=add-recent-github-activity
      - check-success=update-readme-with-blog
      - check-success=compress-images
      - check-success=github-actions
    actions:
      merge:
        method: merge
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict
  - name: delete head branch after merge
    conditions: []
    actions:
      delete_head_branch: {}
