queue_rules:
  - name: default
    queue_conditions:
      - base=main
      - check-success-or-neutral=Deadpendency Check
    merge_conditions:
      - check-success-or-neutral=Deadpendency Check
      - check-success=Dependency Review
    merge_method: merge

pull_request_rules:
  - name: warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        add:
          - conflict

  - name: auto-merge
    conditions:
      - base=main
      - -draft
      - -conflict
    actions:
      queue:
        name: default

priority_rules:
  - name: github-actions PRs
    conditions:
      - author~=github-actions
    priority: 2500
    allow_checks_interruption: true
  - name: dependabot PRs
    conditions:
      - author~=dependabot
    priority: 2250
    allow_checks_interruption: true
