---

# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration
#
# required:     If true, this hook cannot be skipped via the SKIP
#               environment variable
# quiet:        If true, this hook does not display any output unless
#               it warns/fails
# description:  Message displayed while hook is running.
#
# Within a hook category, there is a special type of hook
# configuration that applies to all hooks in the category. This
# configuration looks like a normal hook configuration, except it has
# the name ALL:
#
# PreCommit:
#   ALL:
#     problem_on_unmodified_line: warn
#     requires_files: true
#     required: false
#     quiet: false
#
# SKIP=RuboCop git commit
# ONLY=RuboCop git commit
# OVERCOMMIT_DISABLE=1 ./my-custom-script

CommitMsg:
  HardTabs:
    enabled: true
  MessageFormat:
    enabled: false
    pattern: '\[#(\d+)\](.+)'
    expected_pattern_message: '[#<Issue Id>] <Commit Message Description>'
    sample_message: '[#1234] Refactored Onboarding flow'
  RussianNovel:
    enabled: true
  SpellCheck:
    enabled: true
    install_command: 'brew install hunspell'
  TextWidth:
    enabled: true
    max_subject_width: 50

PreCommit:
  ALL:
    # report: report errors/warnings as-is regardless of line location (default)
    # warn: report errors as warnings if they are on lines you didn't modify
    problem_on_unmodified_line: warn
  BrokenSymlinks:
    enabled: true
  BundleAudit:
    enabled: true
  BundleCheck:
    enabled: true
  BundleOutdated:
    enabled: true
  CaseConflicts:
    enabled: true
  FixMe:
    enabled: true
  ForbiddenBranches:
    enabled: false
  HardTabs:
    enabled: true
  ImageOptim:
    enabled: true
    required_executable: 'svgo'
    install_command: 'brew install svgo'
  LineEndings:
    enabled: true
  LocalPathsInGemfile:
    enabled: true
  Markdownlint:
    enabled: true
    required_executable: 'markdownlint'
    install_command: 'npm install --global markdownlint-cli'
  Mdl:
    enabled: true
  ToDos:
    enabled: false
    quiet: false
    required_executable: 'check-todos'
  TrailingWhitespace:
    enabled: true

PostCheckout:
  BundleInstall:
    enabled: true
  IndexTags:
    enabled: true
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PostCommit:
  BundleInstall:
    enabled: true
  GitGuilt:
    enabled: true
    requires_files: false
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PostMerge:
  BundleInstall:
    enabled: true
  IndexTags:
    enabled: true
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PostRewrite:
  BundleInstall:
    enabled: true
  IndexTags:
    enabled: true
  SubmoduleStatus:
    enabled: true
    quiet: false
    recursive: true

PrePush:
  ProtectedBranches:
    enabled: true

PreRebase:
  MergedCommits:
    enabled: true
