---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # General
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: mixed-line-ending # Replaces or checks mixed line ending.
      - id: trailing-whitespace

      # Json
      - id: check-json
      - id: pretty-format-json # Checks that all your JSON files are pretty.

  # General

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.3.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package.lock.json

  - repo: https://github.com/sirosen/texthooks
    rev: 0.3.1
    hooks:
      - id: fix-smartquotes
      - id: fix-ligatures

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        stages: [commit]

  # Git

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint

  # YAML

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.27.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yml]

  # Mixed

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: git-check # Configure in .gitattributes
      - id: script-must-have-extension
      - id: script-must-not-have-extension
      - id: shellcheck
        args: [--external-sources, --format=gcc, --shell=bash]
      - id: shfmt

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: remove-crlf
      - id: remove-tabs
        exclude: .git/COMMIT_EDITMSG

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.17.1
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
      - id: check-readthedocs
