---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          # General
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-docstring-first
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace

          # Json
          - id: check-json

    # General

    - repo: https://github.com/Yelp/detect-secrets
      rev: v1.5.0
      hooks:
          - id: detect-secrets
            args: [--baseline, .secrets.baseline]
            exclude: package.lock.json

    - repo: https://github.com/sirosen/texthooks
      rev: 0.6.7
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            stages: [pre-commit]

    # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    # Mixed

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          - id: git-check # Configure in .gitattributes
          - id: script-must-have-extension
          - id: script-must-not-have-extension
          - id: shellcheck
            args: [--external-sources, --format=gcc, --shell=bash]
          - id: shfmt

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.29.4
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.21.2
      hooks:
          - id: gitleaks

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.4
      hooks:
          - id: actionlint

    # FIXME: Figure out why ignoring config.
    #    - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    #      rev: 2.6.1
    #      hooks:
    #          - id: editorconfig-checker

    - repo: https://github.com/RyoWakabayashi/pre-commit-mirrors-textlint
      rev: v12.2.1
      hooks:
          - id: textlint
            additional_dependencies:
                [
                    'textlint',
                    'textlint-plugin-latex2e',
                    'textlint-filter-rule-comments',
                    'textlint-rule-alex',
                    'textlint-rule-apostrophe',
                    'textlint-rule-common-misspellings',
                    'textlint-rule-diacritics',
                    'textlint-rule-doubled-spaces',
                    'textlint-rule-editorconfig',
                    'textlint-rule-en-capitalization',
                    'textlint-rule-en-spell',
                    'textlint-rule-max-number-of-lines',
                    'textlint-rule-no-dead-link',
                    'textlint-rule-no-empty-section',
                    'textlint-rule-no-start-duplicated-conjunction',
                    'textlint-rule-no-todo',
                    'textlint-rule-stop-words',
                    'textlint-rule-terminology',
                    'textlint-rule-write-good',
                    'textlint-rule-unexpanded-acronym',
                    '@textlint-rule/textlint-rule-no-duplicate-abbr',
                    '@textlint-rule/textlint-rule-no-invalid-control-character',
                ]

    - repo: https://github.com/streetsidesoftware/cspell-cli
      rev: v8.15.2
      hooks:
          - id: cspell

    - repo: https://github.com/mxab/pre-commit-trivy.git
      rev: v0.13.0
      hooks:
          - id: trivyfs-docker
            args:
                - --ignore-unfixed
                - . # last arg indicates the path/file to scan
            stages: [pre-push]
