# yamllint disable-line rule:document-start
name: Add Latest Blog Posts

on:
  schedule:
    - cron: 0 0 * * * # every day at midnight
  workflow_dispatch: # Run workflow manually directly via the Github Actions Workflow page.

concurrency:
  group: blog-post
  cancel-in-progress: true

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v7
      - uses: gautamkrishnar/blog-post-workflow@1.9.6
        with:
          feed_list: "https://proinsias.github.io/feed.xml"
