# yamllint disable-line rule:document-start
name: Pull Requests & Pushes

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  github-actions:
    name: GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: ${{ runner.os }}-gem-

      - name: Detect Secrets
        uses: reviewdog/action-detect-secrets@v0.12
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      # - name: pre-commit
      #   uses: pre-commit/action@v2.0.2
